# Generated by Django 2.2.16 on 2022-08-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-slug']},
        ),
    ]
